name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Generate code with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      value: |
        - OS: 
        - Go version: 
        - protoc-gen-go-mcp version: 
        - buf version: 
    validations:
      required: true

  - type: textarea
    id: proto
    attributes:
      label: Proto Files
      description: If applicable, provide the relevant .proto files
      render: protobuf

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: If applicable, provide your buf.gen.yaml or relevant configuration
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Error Output/Logs
      description: If applicable, add error messages or log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.