name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bazel
      uses: useblacksmith/setup-bazel@v1

    - name: Build and test
      run: bazelisk test //...
